import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container:{
        flex:1,
        marginHorizontal:5,
        backgroundColor:'#fff7fd',
    },
    name:{
        textAlign:'center',
        fontWeight:'bold',
        fontSize:25,
        marginBottom:9,
        marginTop:8,
    },
    loc_title:{
        marginTop:8,
        fontSize:16,
        fontWeight:'bold',
        color:'#774F9E',
    },
    location:{
        color:'black',
        fontWeight:'400',
    },
    level_title:{
        marginTop:8,
        fontSize:16,
        fontWeight:'bold',
        color:'#774F9E',
    },
    level:{
        color:'black',
        fontWeight:'400',
    },
    content_title:{
        fontWeight:'bold',
        fontSize:23,
        backgroundColor:'white',
        textAlign:'center',
    },
    scroll:{
        backgroundColor:'white',
        padding:10,
        borderRadius:7,
        marginTop:20,
    },
    button_container:{
        flexDirection:'row',
        justifyContent:'space-around',
        margin:10,
    },
    button_text:{
        fontSize:22,
        marginLeft:12,
        color:'#ffdef9',
    },
    button:{
        flex:1,
        padding:8,
        borderRadius:8,
        backgroundColor:'#774F9E',
        flexDirection:'row',
        margin:5,
        justifyContent:'center',
        alignItems:'center'
    },
    submit_container:{
        flexDirection:'row',
        alignItems:'center',
    }

})